project:
  type: website

website:
  title: "reprodev"
  navbar:
    left:
      - href: index.qmd
        text: About
      - schedule.qmd
      - lectures.qmd
      - tutorial_1.qmd
      - tutorial_2.qmd
      - tutorial_3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



